services:
  database:
    image: postgres:14-alpine
    container_name: database
    environment:
      POSTGRES_USER: k0fanov36
      POSTGRES_PASSWORD: k0fanov36
      POSTGRES_DB: yakuninapp
    ports:
      - 5432:5432

  server:
    container_name: server
    build:
      context: ./backend/server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database